

#include "fmindex/encodedtext.h"

#include <cstdio>
#include <fstream>

#include "gtest/gtest.h"

using namespace std;

TEST(EncodeTextTest, Small_5) {
    string text = "AGATCGAATCC$";

    Alphabet<5> sigma(text);

    EncodedText<5> eText(sigma, text);

    ASSERT_EQ(eText.decodeText(sigma), text);
}

TEST(EncodeTextTest, Medium_5) {
    string text = "AGATCGAATCCGGACAGAGATTTTGGGGAAACAAGAGAGACCCGAAGAGAGTTT$";

    Alphabet<5> sigma(text);

    EncodedText<5> eText(sigma, text);

    ASSERT_EQ(eText.decodeText(sigma), text);
}

TEST(EncodeTextTest, Large_5) {
    string text =
        "AGATCGAATCCGGACAGAGATTTTGGGGAAACAAGAGAGACCCGAAGAGAGTTTAAAAGGAAGAGAGATT"
        "TTTCCCCCCCCCCCCAGAGAAGACCCAGAGAGAGAGCCAGAACATACTGTTGTCCATTTCGCGGGGTCGA"
        "GAGACTGGCTCGCATTTAGTAGGGCGGGAGTAGTCTAGTTCATCGATTCTGTCTCTGGTGATGTAAGGGA"
        "GTTATTAGCTCGAGGGGTCGGCTGTGAAACGGATAGTGCTTTTTTTCGGTCCTCTAGCTGATTCTTTACG"
        "GGTTGTAACGTACCTTGAAACTTGAGCTATTGGCGTAGGGGCGGCAACCAAAGGCAATTTTTAGAACTTA"
        "TGCAGTTGAAATAATACGGGTAGCAAGCGAGAACTGAGTGCATGCCAAGACGCTTCCCAGAGTATCACTT"
        "CTTATATGAACAGGGGGAGTGTAGCAATTAGGTAATGTTTAGAGCGCCGAGACTTTTCGTCTAGTTACAG"
        "GACCTCAGGGAACCTCTTGGATTCTAGGAGTGTGACGCTGGTATTCCCCTATTAGGAAACACATTTTGCA"
        "AGCGAATGGGTTAAGAGCATGGTACAAGAAATCGAGCTACAGGAGTGCAGATTATTGTTGTAAGGTGGAG"
        "AAGTAGGCGATACAATTGGGGTGCGCATATGAACTTAACTAAAAGGTGGCATCGAGTAAGACAGTTGAAT"
        "GAAGCGTTAATAAATTTAAGACCCGTGCTTTAACCGAAAGACATTGATTCGCTATCGCGCCCATTGCTCG"
        "CTAGAATAAAGTGAACCCAACTGGTCGTAATAATGTGGGGCCAGACTTGGCACCGGATCGTGTGAAGAGG"
        "GGAACGTTCAGATAATGCAGGACTCACGGAGGTTAGGTTGTACTGCGCAGGCCAGTGGCGAGTTAGCGTG"
        "ATTTACCGCGTGACATATGAGGATGCGGGACGCATCTATGTTGATCTCTTGGCGAGGTATATGATCGCGA"
        "TTGAGTCTCTTCGAACTGGCCGATTTTGTCTTGTACGGGGGTTGGGGTTGGGTTGTTGGAGAATATAATA"
        "CGTGAGAGTTGGAGGGGAGGAAGTATCTTAGCGGGATAAGGCGAGGTCCGATTAAATCACATAGAGATCG"
        "CGGAATAAGTGCTAACTGGTTCGCTAATAAGCGATCAGCGGCGGCGATCGAGGTGTCTCGTCTTCAATCT"
        "TGATAATGGTAACTTTGCTCCTCAGAGCTGGCTGGTAGCTCATTGAAAAATCAGGTAGCCTTCTGGGGAG"
        "ATTTACGTGTAACGGACGCAACCGCTCACCACTTTAAACTCTCTATGCGACTTTGTATTTACTGGCTACA"
        "GTTTCTGGAGCATAGTCACGGCTATTGGGCAGTGTCTGGC$";

    Alphabet<5> sigma(text);
    EncodedText<5> eText(sigma, text);

    ASSERT_EQ(eText.decodeText(sigma), text);
}

TEST(EncodeTextTest, Large_21) {
    string text =
        "MSLAAYCVICCRRIGTSTSPPKSGTHWRDIRNIIKFTGSLILGGSLFLTYEVLALKKAVTLDTQVVEREK"
        "MKSYIYVHTVSLDKGENHGIAWQARKELHKAVRKVLATSAKILRNPFADPFSTVDIEDHECAVWLLLRKS"
        "KSDDKTTRLEAVREMSETHHWHDYQYRIIAQACDPKTLIGLARSEESDLRFFLLPPPLPSLKEDSSTEEE"
        "LRQLLASLPQTELDECIQYFTSLALSESSQSLAAQKGGLWCFGGNGLPYAESFGEVPSATVEMFCLEAIV"
        "KHSEISTHCDKIEANGGLQLLQRLYRLHKDCPKVQRNIMRVIGNMALNEHLHSSIVRSGWVSIMAEAMKS"
        "PHIMESSHAARILANLDRETVQEKYQDGVYVLHPQYRTSQPIKADVLFIHGLMGAAFKTWRQQDSEQAVI"
        "EKPMEDEDRYTTCWPKTWLAKDCPALRIISVEYDTSLSDWRARCPMERKSIAFRSNELLRKLRAAGVGDR"
        "PVVWISHSMGGLLVKKMLLEASTKPEMSTVINNTRGIIFYSVPHHGSRLAEYSVNIRYLLFPSLEVKELS"
        "KDSPALKTLQDDFLEFAKDKNFQVLNFVETLPTYIGSMIKLHVVPVESADLGIGDLIPVDVNHLNICKPK"
        "KKDAFLYQRTLQFIREALAKDLENMSLAAYCVICCRRIGTSTSPPKSGTHWRDIRNIIKFTGSLILGGSL"
        "FLTYEVLALKKAVTLDTQVVEREKMKSYIYVHTVSLDKGENHGIAWQARKELHKAVRKVLATSAKILRNP"
        "FADPFSTVDIEDHECAVWLLLRKSKSDDKTTRLEAVREMSETHHWHDYQYRIIAQACDPKTLIGLARSEE"
        "SDLRFFLLPPPLPSLKEDSSTEEELRQLLASLPQTELDECIQYFTSLALSESSQSLAAQKGGLWCFGGNG"
        "LPYAESFGEVPSATVEMFCLEAIVKHSEISTHCDKIEANGGLQLLQRLYRLHKDCPKVQRNIMRVIGNMA"
        "LNEHLHSSIVRSGWVSIMAEAMKSPHIMESSHAARILANLDRETVQEKYQDGVYVLHPQYRTSQPIKADV"
        "LFIHGLMGAAFKTWRQQDSEQAVIEKPMEDEDRYTTCWPKTWLAKDCPALRIISVEYDTSLSDWRARCPM"
        "ERKSIAFRSNELLRKLRAAGVGDRPVVWISHSMGGLLVKKMLLEASTKPEMSTVINNTRGIIFYSVPHHG"
        "SRLAEYSVNIRYLLFPSLEVKELSKDSPALKTLQDDFLEFAKDKNFQVLNFVETLPTYIGSMIKLHVVPV"
        "ESADLGIGDLIPVDVNHLNICKPKKKDAFLYQRTLQFIREALAKDLENMEQTDCKPYQPLPKVKHEMDLA"
        "YTSSSDESEDGRKPRQSYNSRETLHEYNQELRMNYNSQSRKRKEVEKSTQEMEFCETSHTLCSGYQTDMH"
        "SVSRHGYQLEMGSDVDTETEGAASPDHALRMWIRGMKSEHSSCLSSRANSALSLTDTDHERKSDGENGFK"
        "FSPVCCDMEAQAGSTQDVQSSPHNQFTFRPLPPPPPPPHACTCARKPPPAADSLQRRSMTTRSQPSPAAP"
        "APPTSTQDSVHLHNSWVLNSNIPLETRHFLFKHGSGSSAIFSAASQNYPLTSNTVYSPPPRPLPRSTFSR"
        "PAFTFNKPYRCCNWKCTALSATAITVTLALLLAYVIAVHLFGLTWQLQPVEGELYANGVSKGNRGTESMD"
        "TTYSPIGGKVSDKSEKKVFQKGRAIDTGEVDIGAQVMQTIPPGLFWRFQITIHHPIYLKFNISLAKDSLL"
        "GIYGRRNIPPTHTQFDFVKLMDGKQLVKQDSKGSDDTQHSPRNLILTSLQETGFIEYMDQGPWYLAFYND"
        "GKKMEQVFVLTTAIEIMDDCSTNCNGNGECISGHCHCFPGFLGPDCARDSCPVLCGGNGEYEKGHCVCRH"
        "GWKGPECDVPEEQCIDPTCFGHGTCIMGVCICVPGYKGEICEEEDCLDPMCSNHGICVKGECHCSTGWGG"
        "VNCETPLPVCQEQCSGHGTFLLDAGVCSCDPKWTGSDCSTELCTMECGSHGVCSRGICQCEEGWVGPTCE"
        "ERSCHSHCTEHGQCKDGKCECSPGWEGDHCTIAHYLDAVRDGCPGLCFGNGRCTLDQNGWHCVCQVGWSG"
        "TGCNVVMEMLCGDNLDNDGDGLTDCVDPDCCQQSNCYISPLCQGSPDPLDLIQQSQTLFSQHTSRLFYDR"
        "IKFLIGKDSTHVIPPEVSFDSRRACVIRGQVVAIDGTPLVGVNVSFLHHSDYGFTISRQDGSFDLVAIGG"
        "ISVILIFDRSPFLPEKRTLWLPWNQFIVVEKVTMQRVVSDPPSCDISNFISPNPIVLPSPLTSFGGSCPE"
        "RGTIVPELQVVQEEIPIPSSFVRLSYLSSRTPGYKTLLRILLTHSTIPVGMIKVHLTVAVEGRLTQKWFP"
        "AAINLVYTFAWNKTDIYGQKVWGLAEALVSVGYEYETCPDFILWEQRTVVLQGFEMDASNLGGWSLNKHH"
        "ILNPQSGIIHKGNGENMFISQQPPVISTIMGNGHQRSVACTNCNGPAHNNKLFAPVALASGPDGSVYVGD"
        "FNFVRRIFPSGNSVSILELSTSPAHKYYLAMDPVSESLYLSDTNTRKVYKLKSLVETKDLSKNFEVVAGT"
        "GDQCLPFDQSHCGDGGRASEASLNSPRGITVDRHGFIYFVDGTMIRKIDENAVITTVIGSNGLTSTQPLS"
        "CDSGMDITQVRLEWPTDLAVNPMDNSLYVLDNNIVLQISENRRVRIIAGRPIHCQVPGIDHFLVSKVAIH"
        "STLESARAISVSHSGLLFIAETDERKVNRIQQVTTNGEIYIIAGAPTDCDCKIDPNCDCFSGDGGYAKDA"
        "KMKAPSSLAVSPDGTLYVADLGNVRIRTISRNQAHLNDMNIYEIASPADQELYQFTVNGTHLHTLNLITR"
        "DYVYNFTYNSEGDLGAITSSNGNSVHIRRDAGGMPLWLVVPGGQVYWLTISSNGVLKRVSAQGYNLALMT"
        "YPGNTGLLATKSNENGWTTVYEYDPEGHLTNATFPTGEVSSFHSDLEKLTKVELDTSNRENVLMSTNLTA"
        "TSTIYILKQENTQSTYRVNPDGSLRVTFASGMEIGLSSEPHILAGAVNPTLGKCNISLPGEHNANLIEWR"
        "QRKEQNKGNVSAFERRLRAHNRNLLSIDFDHITRTGKIYDDHRKFTLRILYDQTGRPILWSPVSRYNEVN"
        "ITYSPSGLVTFIQRGTWNEKMEYDQSGKIISRTWADGKIWSYTYLEKSVMLLLHSQRRYIFEYDQPDCLL"
        "SVTMPSMVRHSLQTMLSVGYYRNIYTPPDSSTSFIQDYSRDGRLLQTLHLGTGRRVLYKYTKQARLSEVL"
        "YDTTQVTLTYEESSGVIKTIHLMHDGFICTIRYRQTGPLIGRQIFRFSEEGLVNARFDYSYNNFRVTSMQ"
        "AVINETPLPIDLYRYVDVSGRTEQFGKFSVINYDLNQVITTTVMKHTKIFSANGQVIEVQYEILKAIAYW"
        "MTIQYDNVGRMVICDIRVGVDANITRYFYEYDADGQLQTVSVNDKTQWRYSYDLNGNINLLSHGKSARLT"
        "PLRYDLRDRITRLGEIQYKMDEDGFLRQRGNDIFEYNSNGLLQKAYNKASGWTVQYYYDGLGRRVASKSS"
        "LGQHLQFFYADLTNPIRVTHLYNHTSSEITSLYYDLQGHLIAMELSSGEEYYVACDNTGTPLAVFSSRGQ"
        "VIKEILYTPYGDIYHDTYPDFQVIIGFHGGLYDFLTKLVHLGQRDYDVVAGRWTTPNHHIWKQLNLLPKP"
        "FNLYSFENNYPVGKIQDVAKYTTDIRSWLELFGFQLHNVLPGFPKPELENLELTYELLRLQTKTQEWDPG"
        "KTILGIQCELQKQLRNFISLDQLPMTPRYNDGRCLEGGKQPRFAAVPSVFGKGIKFAIKDGIVTADIIGV"
        "ANEDSRRLAAILNNAHYLENLHFTIEGRDTHYFIKLGSLEEDLVLIGNTGGRRILENGVNVTVSQMTSVL"
        "NGRTRRFADIQLQHGALCFNIRYGTTVEEEKNHVLEIARQRAVAQAWTKEQRRLQEGEEGIRAWTEGEKQ"
        "QLLSTGRVQGYDGYFVLSVEQYLELSDSANNIHFMRQSEIGRR$";
    Alphabet<21> sigma(text);

    EncodedText<21> eText(sigma, text);

    ASSERT_EQ(eText.decodeText(sigma), text);
}

TEST(EncodeTextTest, VeryLarge_5) {
  

    std::string text = "GC$CGAT"; // Example  string
    std::string repeat = "ACGTAAATTTGGGCCC";
   
    for(int i = 0; i < 10000; i++){
        text += repeat;
    }
    
    Alphabet<5> sigma(text);

    EncodedText<5> eText(sigma, text);

    ASSERT_EQ(eText.decodeText(sigma), text);

    string fn = "encodedtexttest.test";
    eText.write(fn);

    EncodedText<5> eText2;

    eText2.read(fn);
    ASSERT_EQ(eText2.decodeText(sigma), text);
}
